/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  auth: {
    Auth: () => import('#controllers/auth/auth_controller'),
  },
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  leaveRequests: {
    LeaveRequests: () => import('#controllers/leave_requests/leave_requests_controller'),
  },
}
